---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: packer-debian
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
            - git
            - wget
            - curl
            - vim
      state: present
      when: ansible_os_family == 'Debian'
